spring.datasource.url=jdbc:postgresql://localhost:5432/eventshubdb
spring.datasource.username=eventsuser
spring.datasource.password=Passwordtoeventshub
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP pool settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.pool-name=EventshubConnectionPool
logging.level.com.zaxxer.hikari=DEBUG

#Mpesa Credentials
mpesa.appKey=XMrUS9ZHgVxAzqJwDLVthLSU70swM5v
mpesa.appSecret=fcGO70SvDM3zIK8gmtLGW
mpesa.businessShortCode=174379
mpesa.passKey=bfb279f9aa9bdbcf158e97dd71
mpesa.callbackUrl=https://example.com/api/payments/confirmation
mpesa.timeoutUrl=https://example.com/api/payments/timeout