spring.datasource.url=jdbc:postgresql://localhost:5432/eventshubdb
spring.datasource.username=eventsuser
spring.datasource.password=Passwordtoeventshub
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP pool settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.pool-name=EventshubConnectionPool
logging.level.com.zaxxer.hikari=DEBUG

#Mpesa Credentials
mpesa.appKey=XMrUS9ZHgVxAzqJwDLVthLSU70swM5vjkAhaN72iLKgsvzTR
mpesa.appSecret=fcGO70SvDM3zIK8gmtLGWxR2zwWVKBVSdN8dSYcU91U1WJ0Whs14YIzyvY1ttbOK
mpesa.businessShortCode=174379
mpesa.passKey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.callbackUrl=https://example.com/api/payments/confirmation
mpesa.timeoutUrl=https://example.com/api/payments/timeout